### ISSUE TITLE
「企画ページ」内、各企画の開催場所の表記改善

### ISSUE THREAD

**Issue by aoba-s** [AKABANEDAI-FES/2024-akabanedai-fes#19]
### 💡 提案の概要

開催場所の後ろに（INIAD）とか（WELLB）のように施設名を入れてほしい
例：2317教室（INIAD）
　　多目的室1（HELSPO）

### 🥳 提案の目的

どの建物の企画なのかが一目でわかるようになるため見やすい

### 🖋️ 補足事項

https://akabanedai-fes.slack.com/archives/C07CEJV7ZEC/p1729097502739879

**Comment by tmts0312** [comment]
補足
・4ケタ数字の教室は全て（INIAD）
・学生ホールは（WELLB）
・INIActorsは（INIAD）
・ECZルームは（WELLB）
・2から始まる5ケタ数字(20304とか)の教室は全て（WELLB）
・3から始まる5ケタ数字(30301とか)の教室は全て（HELSPO）
・第1,第2会議室は（INIAD）
・多目的室1,多目的室2は（HELSPO）
・プレゼンテーションハブは（INIAD）
・実験工房は（WELLB）
・アリーナは（HELSPO）
・保育実習室は（WELLB）

**Comment by yu7400ki** [comment]
@tmts0312 
~~「ホール」は「INIAD ホール」とかのほうが良いですかね？~~
>  INIActorsは（INIAD）

書いてありましたね……
