### ISSUE TITLE
使い回す要素をコンポーネントに統一する

### ISSUE THREAD

**Issue by aoba-s** [AKABANEDAI-FES/2024-akabanedai-fes#30]
### 💡 提案の概要

タイトルやサブタイトルなど、使い回す要素はコンポーネントにまとめる。

### 🥳 提案の目的

デザインの揺れを解消できる。
一度作ったものをもう一度作らずに済む。

### 🖋️ 補足事項

例
https://github.com/AKABANEDAI-FES/2024-akabanedai-fes/blob/f05ddef6da2b0297c839e95be6dcdd850f70eec3/src/app/(programs)/_page.module.css#L23-L27

https://github.com/AKABANEDAI-FES/2024-akabanedai-fes/blob/f05ddef6da2b0297c839e95be6dcdd850f70eec3/src/app/guest-guide/guest-guide.module.css#L1-L6

**Comment by yu7400ki** [comment]
リファクタリングするコストと見合う算段がついたら考えます
